# Generated by Django 5.2 on 2025-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0, max_length=20)),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
